<?php

// $Id$
function islandora_video_sp_menu() {
  $items['admin/settings/islandora_video_sp'] = array(
    'title' => 'Islandora Video Solution Pack Admin',
    'description' => 'Configure Islandora Video Module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_video_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'islandora_video.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  $items['islandora/video/ffm'] = array(
    'page callback' => 'update_ffm_div',
    'access arguments' => array('view fedora collection'),
    'file' => 'islandora_video.admin.inc',
    'type' => MENU_CALLBACK,
  );
  $items['islandora/video/exif'] = array(
    'page callback' => 'update_exif_div',
    'access arguments' => array('view fedora collection'),
    'file' => 'islandora_video.admin.inc',
    'type' => MENU_CALLBACK,
  );
  $items['islandora/video/theora'] = array(
    'page callback' => 'update_theora_div',
    'access arguments' => array('view fedora collection'),
    'file' => 'islandora_video.admin.inc',
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function islandora_video_sp_required_fedora_objects() {
  module_load_include('inc', 'fedora_repository', 'fedora_repository.solutionpacks');
  // Add the form and associate it to the content model
  $module_path = drupal_get_path('module', 'islandora_video_sp');
  $form_name = 'Islandora Video MODS Form';
  $form_xml = file_get_contents("$module_path/install_files/MODS_VIDEO_FORM.xml");
  solution_pack_add_form($form_name, $form_xml);
  solution_pack_add_form_association('islandora:sp_videoCModel', $form_name);





  return array(
    'islandora_video_sp' => array(
      'module' => 'islandora_video_sp',
      'title' => 'Islandora Video Solution Pack',
      'objects' => array(
        array(
          'foxml_file' => "$module_path/install_files/islandora_sp_videoCModel.xml",
          'pid' => 'islandora:sp_videoCModel',
          'dsid' => NULL,
          'datastream_file' => NULL,
          'dsversion' => NULL,
        ),
        array(
          'pid' => 'islandora:video_collection',
          'label' => t('Video Collection'),
          'cmodel' => 'islandora:collectionCModel',
          'parent' => 'islandora:root',
          'datastreams' => array(
            array(
              'dsid' => 'COLLECTION_POLICY',
              'datastream_file' => "$module_path/install_files/video_collection_policy.xml",
            ),
            array(
              'dsid' => 'TN',
              'datastream_file' => "$module_path/images/Crystal_Clear_filesystem_folder_video.png",
              'mimetype' => 'image/png',
            ),
          ),
        ),
      ),
    ),
  );
}

function islandora_video_sp_form_fedora_repository_ingest_form_alter(&$form, &$form_state) {

  if ($form['content_model_pid']['#value'] == 'islandora:sp_videoCModel') {
    $form['upload'] = array(
      'upload' => array(
        '#weight' => -99,
        '#type' => 'yui_uploader',
        '#required' => TRUE, // If FALSE the user can submit the form without uploading any files, if true at least one file must be uploaded.
        '#width' => '100px', // The width of the upload button.
        '#height' => '40px', // The height of the rendered button
        '#extensions' => array('ogg', 'mp4', 'mov', 'qt', 'm4a'), // Limit uploads to matching file extensions. Examples array('jpg', 'xml')
        '#multiple_files' => FALSE, // Allow multiple files to selected at once
      ),
    );
    array_unshift($form['#validate'], 'manage_yui_uploads');
    if (!variable_get('video_retain_original', TRUE)) {
      $form['#validate'][] = 'video_remove_original';
    }
    $form['submit']['#value'] = t("Create Video Object");
  }
}

function manage_yui_uploads($form, &$form_state) {
  $upload_files = $form_state['storage']['yui_uploader'];
  foreach ($upload_files as $file) {
    $path = $file->filepath;
    $ext = pathinfo($path, PATHINFO_EXTENSION);
    $form_state['values']['ingest-file-location'] = $path;
  }
}

function video_remove_original($form, &$form_state) {
  $form_state['values']['ingest-file-location'] = NULL;
}