<?php

/**
 * @file
 * Hooks and callbacks for this module.
 */

/**
 * Implements hook_menu().
 */
function islandora_video_menu() {
  $items = array();
  $items['admin/islandora/video'] = array(
    'title' => 'Video Solution Pack',
    'description' => 'Configure the Video solution pack',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_video_admin'),
    'access arguments' => array('administer site configuration'),
    'file' => 'includes/admin.form.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implements hook_theme().
 */
function islandora_video_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_video' => array(
      'template' => 'theme/islandora-video',
      'file' => 'theme/theme.inc',
      'pattern' => 'islandora_video__',
      'variables' => array('object' => NULL),
    ),
  );
}

/**
 * Implements hook_islandora_required_objects().
 */
function islandora_video_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_video');
  // Video Content Model.
  $video_content_model = $connection->repository->constructObject('islandora:sp_videoCModel');
  $video_content_model->owner = 'fedoraAdmin';
  $video_content_model->label = 'Islandora Video Content Model';
  $video_content_model->models = 'fedora-system:ContentModel-3.0';
  // ISLANDORACM Datastream.
  $datastream = $video_content_model->constructDatastream('ISLANDORACM', 'X');
  $datastream->label = 'Islandora content model';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_video_cmodel.xml", FALSE);
  $video_content_model->ingestDatastream($datastream);
  // DS-COMPOSITE-MODEL Datastream.
  $datastream = $video_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_video_ds_composite_model.xml", FALSE);
  $video_content_model->ingestDatastream($datastream);
  // Video Collection.
  $video_collection = $connection->repository->constructObject('islandora:video_collection');
  $video_collection->owner = 'fedoraAdmin';
  $video_collection->label = 'Video Collection';
  $video_collection->models = 'islandora:collectionCModel';
  $video_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  // Collection Policy Datastream.
  $datastream = $video_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->label = 'Collection policy';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_video_collection_policy.xml", FALSE);
  $video_collection->ingestDatastream($datastream);
  // TN Datastream.
  $datastream = $video_collection->constructDatastream('TN', 'M');
  $datastream->label = 'Thumbnail';
  $datastream->mimetype = 'image/png';
  $datastream->setContentFromFile("$module_path/images/folder.png", FALSE);
  $video_collection->ingestDatastream($datastream);
  return array(
    'islandora_video' => array(
      'title' => 'Islandora Video',
      'objects' => array(
        $video_content_model,
        $video_collection,
      ),
    ),
  );
}

/**
 * Implements hook_islandora_xml_form_builder_forms().
 */
function islandora_video_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_video');
  return array(
    'Video MODS form' => array(
      'form_file' => "$module_path/xml/islandora_video_form_mods.xml",
    ),
  );
}

/**
 * Implements hook_islandora_xml_form_builder_form_associations().
 */
function islandora_video_islandora_xml_form_builder_form_associations() {
  return array(
    'islandora_video_mods_form' => array(
      'content_model' => 'islandora:sp_videoCModel',
      'form_name' => 'Video MODS form',
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'template' => FALSE,
    ),
  );
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_video_islandora_sp_videoCModel_islandora_view_object($object, $page_number, $page_size) {
  $output = theme('islandora_video', array('object' => $object));
  return array('' => $output);
}

/**
 * Implements hook_CMODEL_PID_islandora_object_ingested().
 */
function islandora_video_islandora_sp_videoCModel_islandora_object_ingested($object) {
  module_load_include('inc', 'islandora_video', 'includes/derivatives');
  islandora_video_create_all_derivatives($object);
}

/**
 * Implements hook_islandora_ingest_steps().
 */
function islandora_video_islandora_sp_videoCModel_islandora_ingest_steps() {
  return array(
    'islandora_video_upload' => array(
      'weight' => 10,
      'type' => 'form',
      'form_id' => 'islandora_video_upload_form',
      'module' => 'islandora_video',
      'file' => 'includes/video_upload.form.inc',
    ),
  );
}
